common:
    cert_domain: ENC[AES256_GCM,data:PXrD1XMR6vXr/0sKgJo=,iv:8muki8IzEo3/T32Y27sYNTNo7n8LV9CALEJnaBiI+Kc=,tag:oldJsP8HM+EfEijp54MzBw==,type:str]
    cloudflare_ips:
        - ENC[AES256_GCM,data:AJY4+hxP09oNvy8cjRlh,iv:+VgKS9QqcHe4bY3AGgWQVYk57kMRmw4rzga0Iuo6KYM=,tag:AXYcfqQISSPQZNZA4GMsSA==,type:str]
        - ENC[AES256_GCM,data:aXiERwo1OQ2AvighbjsY,iv:j9Q4XC8zCl1NR6zN6m7fpx1yWhC4BBuaA/98aya3ZTs=,tag:OEUjQPEMfdL7uPDSE4X4zg==,type:str]
        - ENC[AES256_GCM,data:LI/utOE8mseIOb/VII05,iv:0+4YBzKZw/gqjXzNMwudMMBD6veqOAbqM7e1x+3WyBg=,tag:YCUXIXhdKIa6JmCH1ll8AA==,type:str]
        - ENC[AES256_GCM,data:7GekMnYgPlHTRSnU3w==,iv:RhGw/0qj6eA6DvYOOR3YDmp7jdnRAmCCKmHzbifRvc8=,tag:XitSQY2DWSvCLh5Stb1IEA==,type:str]
        - ENC[AES256_GCM,data:kwc0OuECTlo9fnacGP+I,iv:1j/yPyU/+51o1k5HC7s/xaIQ2Wm/QcQzZto4L+J8Los=,tag:LGsidh5t8i5bErlV0aWEtA==,type:str]
        - ENC[AES256_GCM,data:NOUTxYPARmdTP+5rqjfVww==,iv:fi5Lx+q5fzKuZRU9J1sqaGzQIkRR+H5nBRB/20wfKc0=,tag:laiL749UmB+1iN9wGkcf9w==,type:str]
        - ENC[AES256_GCM,data:OSjkiFlF/UmK8QP8g5of,iv:XzTB7d6y8oOI4myG/Y0I9AyZWE77cgvB6xJFuQZrXVw=,tag:lCG3a3mUBiJWLZ7lP8DLIg==,type:str]
        - ENC[AES256_GCM,data:HvGvvGUCmgOoFPqA9BwS,iv:K8HSpgkEvaHJg5nXfJjF6k/4HewZwQppCdYmLttqVUE=,tag:VtTzYp/yZ8fNdJHqNwKRGg==,type:str]
        - ENC[AES256_GCM,data:G4bt5XDZy7HckIuxLIGgvQ==,iv:xX1jozbZ2Yh0ffKNoMMqiaro8+GpVz/RD3WEiPrc1yk=,tag:BDH2hwqlwko/KXOiXPKzmw==,type:str]
        - ENC[AES256_GCM,data:JKDQZ21YrikkvLY7Bwvs,iv:8fdmvgC6hR9JNFtiOke7pRf1i+RODNAYPzNkhquD9TY=,tag:uOnQ+HEj0qunVPde9dDnTQ==,type:str]
        - ENC[AES256_GCM,data:d/UOH1EOSoq7D2Ny4Ss=,iv:lmi9t7utj+xt1CJSgv7SGxquLUlCpXqSlgPTZFApSlU=,tag:j4ER4R5tnsqDzV+sUcR7EA==,type:str]
        - ENC[AES256_GCM,data:v/Y/qbM6kls4TyPfyg==,iv:m9DXE1XZ5dALkAgnkWHG0CE345JwUVUbTDwe7BJi5Gw=,tag:PQGFwxP4S+nqON1P5akfHA==,type:str]
        - ENC[AES256_GCM,data:hPi54DUko5GFRbb0sg==,iv:YvSzQiJC+gyv/+r82JjAw1OmeAsja2Z6UW/6Rh1iAXU=,tag:0jb0Kx6Qr9l/I+TAFsbHxQ==,type:str]
        - ENC[AES256_GCM,data:qF6jozjl4BUGy8QQ5A==,iv:2aHup+6rY9QnJzkBW3ZkS+3EC/y0f3qmAbKIZaiGgfs=,tag:TBqE885BynPrXOkPZC99qQ==,type:str]
        - ENC[AES256_GCM,data:UnFV2MMnY5MocF+Hvw==,iv:Dkv7GEGtltvtR3mcON06vKMTFlPe2fuKFSjkVMRwdmg=,tag:wx1Cm70N3ER+yu+Q8C0McA==,type:str]
        - ENC[AES256_GCM,data:r4Ef4nJR0pXDnwQ1axw=,iv:lkJyHmNm6BsXzxLUdbYusrghqYHQ+q9PJJrJqxAQvTk=,tag:zIZZV4Ln7U5ReWUgORdrog==,type:str]
        - ENC[AES256_GCM,data:7N6ePcmgGBKC3JTgo4k=,iv:vdLdPBukBRrOdiY+CY/rGjhqkDdtw7G4kTPOYhfB0Ag=,tag:1MSDIAimpQpgFMQkOkiAKg==,type:str]
        - ENC[AES256_GCM,data:wvHahespgrE/ayS5lq8=,iv:Efa2gaMA8pXzJbMdpuSZOnnvqe7O7O4c7sRKTb7ifqY=,tag:9GdFpz1lyhQAlVr5EA3FAQ==,type:str]
        - ENC[AES256_GCM,data:E54j3IUrxDnUGoJyfaI=,iv:vXNWGVgU5E//YnC2/0r2tx3T4t7BXTOp8++Ni1jyFW8=,tag:uwzEBeAv5uM4smbveKg/og==,type:str]
        - ENC[AES256_GCM,data:BEPtqMhqF3w9NJkGCLY=,iv:a+xz/Iu2tOM8VzYKBPLlwxqHZZo7SDYwbuXavDEI4fg=,tag:tDArOilGB2l3t/+vZCNtvw==,type:str]
        - ENC[AES256_GCM,data:7/isiFLP1yapyXhE7+w=,iv:knHiJ04imGYTlo1NUa3+yuYSOprg2QwDBesEaG9BBjo=,tag:m1bI71cPyUhhDmLukaaXsg==,type:str]
        - ENC[AES256_GCM,data:S4JuQo//VN9kCKW6pL0=,iv:GA54jXKLbLaPEFTRVkBzhCjkG5LS+0aCI1RIhQFiC7Y=,tag:2DN9DhDEseyNstR0nbcEEw==,type:str]
    allowed_source_ranges:
        - ENC[AES256_GCM,data:30brMvT4Yj+GAtHD3A==,iv:P3KnVB7pm7Kzww51GItV4NjtUj1pj7qiP/cY1yh3PQk=,tag:Xo5bM662FIzOKxQjp5qrbQ==,type:str]
        - ENC[AES256_GCM,data:042RGrAEV6CQZu0LWw==,iv:Cw02J0hXgUbFi43/C+TuiiWEE2R570tUh9dGYIyX7mU=,tag:3JLUlw9ypP5O4pNVtmpk1w==,type:str]
        - ENC[AES256_GCM,data:CO41h7Uy3IDynfLdvg==,iv:LN20FXjPsyrrNiUuBuBbhmXbTyLnE5ngcdbp4PwVa9g=,tag:0VMohuo4OuRsQ+OsaaqJRw==,type:str]
        - ENC[AES256_GCM,data:csgTWe1PynDYmL0YwQQ=,iv:lQYxSWYncNlw/c1020SimsoszDH7RxWMDlfiLH8s4e8=,tag:L8tDsFag+AOjU2yYny53ig==,type:str]
instances:
    instance1:
        domain: ENC[AES256_GCM,data:7pb/a6LQfqYMV+TBOPbAHNzrtpym8DaJ,iv:4oiCak0sRboIeVYCC/9Sew79DDkKPPnfRH+c2fhmdsE=,tag:uZewBEBpIwPsgdd1gJqRtw==,type:str]
        host: ENC[AES256_GCM,data:59Ja0w3I+g==,iv:a2DQlSjidSDygng/VPIJZzk275cituIdSkBur0Qum/g=,tag:Ut5fpPk6UnDxGhBGiSpmVQ==,type:str]
    instance2:
        domain: ENC[AES256_GCM,data:URNfed3gh5FAngJrHgISRl5p7Pdb7wtH,iv:0TNljI5uubcb+teT/3GOjQACBWpWu2pX2E8WjScARL0=,tag:306OeCknIocnuyX4QW0PzQ==,type:str]
        host: ENC[AES256_GCM,data:07KCvST1mg==,iv:3Y66sZiikz6Olji/1DRwbTnlxTbCg9ch2Yt0vpR+Z/o=,tag:nYGCEfZSM7xqTaE94mPSgA==,type:str]
    instance3:
        domain: ENC[AES256_GCM,data:feNWs1EDUCrQ+rBOXr/uijbj4EcIJUod,iv:G8NtdSRWdNEC3WNKC8XRm7Y4bearCO8oUixMLA5UqzY=,tag:ZMzQzHfLeUFUpAdygO6sVg==,type:str]
        host: ENC[AES256_GCM,data:dT4NTqJG/w==,iv:38IALiYsLlOX4+d82MRFKa8EbYYvdzfOzD6pwwpa/Uk=,tag:9T97r8w3VJ6dqhw7MYFmgA==,type:str]
    instance4:
        domain: ENC[AES256_GCM,data:PZwNGLx4OJ1NIbUJryblwM56rWz1mEo/,iv:3uIPUnptziN3SFNSbJsxKLB6mrGpM2AB5h+MhcaII5Q=,tag:tPikRivHusBf/qr2PuRJ8g==,type:str]
        host: ENC[AES256_GCM,data:AcezocjPEw==,iv:TW18p6aa0iwyJ7hkoJ7eVuNd+cCs8vq+JLGozKJ3Z/Y=,tag:waSPrKuEYBlkH3JRDirIEg==,type:str]
sops:
    age:
        - recipient: age1p9r276rvjh98r93nsvqhzuhlqnawur0j0hn34qmeangcd94mlchqgvm820
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN0pER3oyM2ZQNkdxaWxP
            OWtKYjB1WGxCZ2dpeWRHSHZySmRlcHVIT21RCmpnL2tkTGNMU1RZTmhDT3cvYjQ1
            bXByK3ozR1c5MGhQL1hVWUJPZjhIYXMKLS0tIExpWUdqZE5tcmVOV0lpTEc0alBS
            eFNFajB1MFFiaE5Hc2dMNkg3ODZ0cjgKNZVLA79JDXicVYUbdhQCgx3u185Dp+Mx
            eJLva6GvVW5sz8qUyohilnOwtXKL1feiYsv8oLIV4i1jgDIUMLN2sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T23:04:57Z"
    mac: ENC[AES256_GCM,data:ZF+T2WHVs3NbAGy5V36gVsumet+soUTsrCoylbfaGqDhZDy90dA/CielOLrho6jKPsAcnlJligVYBv4SsK3dCawfcD/kFISrTNA3xwCdbDfJMnc7ngAuAKggpki0Xde5badYgc/onNYpQq+m9X94KsflhZcQqsw8ACmh03hdCz8=,iv:8yFe+wx9zsd/xlS0GqH4rCr/IGzs14z+QluK66oCH5A=,tag:Kq41m/jAxXNvdKAMT4yarA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
